### ISSUE TITLE
Font size issue

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaConference2021#4]
There is a font size issue of paper [49 -Modia-Equation Based Modeling and Domain Specific Algorithms, Hilding Elmqvist, Martin Otter, Andrea Neumayr and Gerhard Hippmann](https://2021.international.conference.modelica.org/proceedings/papers/Modelica2021session1B_paper1.pdf) after first use of `Var` in line 2 of section 2.1. The issue likely is due to an outdated conference template being lately fixed by https://github.com/modelica/conference-templates/pull/33. @MartinOtter

**Comment by sjoelund** [comment]
The papers are finalized and the publishing process already started. Next conference should have even more consistent styles
